# Generated by Django 5.1.15 on 2026-09-27 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hackathon event.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL identifier.', max_length=250, unique=True)),
                ('description', models.TextField(help_text='Detailed description and rules for the event.')),
                ('start_date', models.DateTimeField(help_text='When the hackathon starts.')),
                ('end_date', models.DateTimeField(help_text='When the hackathon officially concludes.')),
                ('registration_deadline', models.DateTimeField(help_text='Last date and time for participants/teams to register.')),
                ('submission_deadline', models.DateTimeField(help_text='Final deadline for submitting projects.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', help_text='Event state: Draft, Open, or Closed.', max_length=20)),
                ('gallery_enabled', models.BooleanField(default=False, help_text='Controls whether submitted projects appear on the public gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Organizer or administrator who created the event.', on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Prize title (e.g., '1st Place', 'Best UI').", max_length=150)),
                ('description', models.CharField(help_text="Prize value or details (e.g., '₹80,000' or 'Cash + Swag').", max_length=255)),
                ('rank', models.PositiveIntegerField(default=1, help_text='Ordering rank (1 for first place, 2 for second place, etc.).')),
                ('event', models.ForeignKey(help_text='Event to which this prize belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
            ],
            options={
                'ordering': ['rank', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Track title.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Specific requirements and guidelines for this track.')),
                ('event', models.ForeignKey(help_text='Event to which this track belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
