# Generated by Django 5.1.15 on 2026-09-27 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Evaluation status: Not Started, In Progress, or Completed.', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('judge', models.ForeignKey(help_text='The judge assigned to evaluate this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='The submitted project to be judged.', on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='submissions.submission')),
            ],
            options={
                'ordering': ['submission__event', 'submission', 'judge'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the rubric criterion (e.g. 'Tier Completion & Correctness').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed evaluation guidance and standards for judges.')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage weight of this criterion (e.g. 40.00). Must sum to 100% per event.', max_digits=5)),
                ('max_score', models.PositiveIntegerField(default=10, help_text='Maximum raw rating score a judge can award (default: 10).')),
                ('event', models.ForeignKey(help_text='The event to which this evaluation rubric belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, help_text='Raw score awarded by the judge, bounded by rubric_criterion.max_score.', max_digits=5)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=2, help_text='Normalized score adjusted for judge harshness/leniency via z-score normalization.', max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, help_text='Optional feedback or justification notes from the judge.')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='The judge assignment this score belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.judgeassignment')),
                ('rubric_criterion', models.ForeignKey(help_text='The specific rubric criterion being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.rubric')),
            ],
            options={
                'ordering': ['assignment', 'rubric_criterion'],
            },
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(fields=('judge', 'submission'), name='unique_judge_submission_assignment'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_rubric_criterion_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assignment', 'rubric_criterion'), name='unique_score_per_assignment_criterion'),
        ),
    ]
