# Generated by Django 5.1.15 on 2026-09-28 08:46

import apps.judging.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_results_visible_during_voting_and_more'),
        ('judging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeassignment',
            name='is_flagged_for_review',
            field=models.BooleanField(default=False, help_text='Flagged for organizer review (e.g. if judge was revoked after scoring).'),
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Organizer notes explaining flag reason.'),
        ),
        migrations.CreateModel(
            name='EventJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Optional target email address if the invitee does not have an account yet.', max_length=254)),
                ('token', models.CharField(db_index=True, default=apps.judging.models.generate_judge_invite_token, help_text='Cryptographically secure unique token for shareable invitation link.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', help_text='Status of the invitation: pending, accepted, declined, revoked.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(help_text='The hackathon event this invitation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='judge_invitations', to='events.event')),
                ('invited_by', models.ForeignKey(help_text='Organizer or admin who created the invitation.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_judge_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The judge user invited or who accepted this invitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_event_judge_user')],
            },
        ),
    ]
