# Generated by Django 5.1.15 on 2026-09-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Project title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Comprehensive project description and technical overview.')),
                ('repo_url', models.URLField(blank=True, help_text='Public repository URL (GitHub, GitLab, etc.).', max_length=500)),
                ('demo_url', models.URLField(blank=True, help_text='Optional live demo URL, hosted app, or video walkthrough.', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', help_text='State of the submission: draft or submitted.', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when project was officially marked as submitted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Denormalized from team.event for query convenience.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event')),
                ('team', models.OneToOneField(help_text='The team submitting this project (one submission per team).', on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='teams.team')),
                ('track', models.ForeignKey(blank=True, help_text='Optional track category selected for this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='events.track')),
            ],
            options={
                'ordering': ['-submitted_at', '-updated_at'],
            },
        ),
    ]
