# Generated by Django 5.1.15 on 2026-09-27 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_results_visible_during_voting_and_more'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('vote_changed', 'Vote Changed'), ('comment_posted', 'Comment Posted'), ('comment_hidden', 'Comment Hidden'), ('comment_unhidden', 'Comment Unhidden'), ('rate_limit_triggered', 'Rate Limit Triggered')], help_text='Type of community action recorded.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured context (old/new score, duplicate flag, client details).')),
                ('target_submission', models.ForeignKey(blank=True, help_text='Target submission affected by this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_audit_logs', to='submissions.submission')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the action (or null for unauthenticated/system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Comment text content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Soft-hidden by organizer for moderation. Remains in database for audit.')),
                ('is_flagged_duplicate', models.BooleanField(default=False, help_text='Flagged as a repeated/near-identical comment for organizer review.')),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_by', models.ForeignKey(blank=True, help_text='Organizer/Admin who hid this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_community_comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Submission being discussed.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.submission')),
                ('user', models.ForeignKey(help_text='Author of the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event the user is registered for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(help_text='Registered participant.', on_delete=django.db.models.deletion.CASCADE, related_name='community_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_registration')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=5, help_text='Rating score from 1 (lowest) to 5 (highest) stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(help_text='Submission being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='submissions.submission')),
                ('user', models.ForeignKey(help_text='Participant who cast the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='community_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('submission', 'user'), name='unique_vote_per_submission_user')],
            },
        ),
    ]
